at_falla:
    path:     /{idAt}/index
    defaults: { _controller: "AtBundle:AtFalla:index" }

at_falla_show:
    path:     /{id}/show
    defaults: { _controller: "AtBundle:AtFalla:show" }

at_falla_new:
    path:     /{idAt}/new
    defaults: { _controller: "AtBundle:AtFalla:new" }

at_falla_edit:
    path:     /{id}/edit
    defaults: { _controller: "AtBundle:AtFalla:edit" }

at_falla_eliminar:
    path:     /{id}/eliminar
    defaults: { _controller: "AtBundle:AtFalla:eliminar" }
