<?php

namespace ATManager\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtRepository extends EntityRepository
{
	public function findByFiltroAt($numero, $personasolicita, $sectorsolicita)
	{

		$em = $this->getEntityManager();
		$query = $em->createQueryBuilder()
		->select('p')
		->from('FrontendBundle:At','a')
		->where('1 = 1');
		if ($numero)
		{
		$query->andWhere('a.id = :id');
		$query->setParameter('id',$numero);
		}
		if ($personasolicita)
		{
		$query->andWhere('a.personasolicita LIKE :personasolicita');
		$query->setParameter('personasolicita','%'.$personasolicita.'%');
		}
		if ($sectorsolicita)
	    {
    	$query->andWhere('a.sectorsolicita = :sectorsolicita');
		$query->setParameter('sectorsolicita',$sectorsolicita);
	    }
	    
		$query->setMaxResults(50);
		$query = $query->getQuery();
		return $query->getResult();
	}
}
