estadio:
    pattern:  /
    defaults: { _controller: "BackendBundle:Estadio:index" }

estadio_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Estadio:show" }

estadio_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Estadio:new" }

estadio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Estadio:edit" }

estadio_eliminar:
    pattern:  /delete/{id}
    defaults: { _controller: "BackendBundle:Estadio:eliminar" }
