prioridad_listado:
    pattern:  /
    defaults: { _controller: "BackendBundle:Prioridad:index" }

prioridad_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Prioridad:show" }

prioridad_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Prioridad:new" }

prioridad_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Prioridad:edit" }

prioridad_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "BackendBundle:Prioridad:eliminar" }    
