proveedor:
    pattern:  /
    defaults: { _controller: "BackendBundle:Proveedor:index" }

proveedor_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Proveedor:show" }

proveedor_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Proveedor:new" }

proveedor_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Proveedor:edit" }

proveedor_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "BackendBundle:Proveedor:eliminar" }
