rol:
    pattern:  /
    defaults: { _controller: "BackendBundle:Rol:index" }

rol_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Rol:show" }

rol_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Rol:new" }

rol_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Rol:edit" }

rol_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "BackendBundle:Rol:eliminar" }    
