sector_listado:
    pattern:  /
    defaults: { _controller: "BackendBundle:Sector:index" }

sector_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:Sector:show" }

sector_new:
    pattern:  /new
    defaults: { _controller: "BackendBundle:Sector:new" }

sector_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BackendBundle:Sector:edit" }

sector_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "BackendBundle:Sector:eliminar" }        
