sectortipo_listado:
    pattern:  /
    defaults: { _controller: BackendBundle:SectorTipo:index }

sectortipo_new:
    pattern:  /new
    defaults: { _controller: BackendBundle:SectorTipo:new }

sectortipo_edit:
    pattern:  /edit/{id}
    defaults: { _controller: BackendBundle:SectorTipo:edit }    

sectortipo_delete:
    pattern:  /delete/{id}
    defaults: { _controller: BackendBundle:SectorTipo:delete }

sectortipo_show:
    pattern:  /{id}/show
    defaults: { _controller: "BackendBundle:SectorTipo:show" }    

sectortipo_eliminar:
    pattern:  /eliminar/{id}
    defaults: { _controller: BackendBundle:SectorTipo:eliminar}    

