<?php

namespace ATManager\AtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtFallaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtFallaRepository extends EntityRepository
{
}
