<?php

namespace ATManager\AtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtHistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtHistoricoRepository extends EntityRepository
{
    public function findByHistoricoPorAt($at)
    {
        $em = $this->getEntityManager();		  	
        $query = $em->createQuery('SELECT h FROM AtBundle:AtHistorico h WHERE h.at = :at order by h.fecha')
            ->setParameter('at', $at);
        $query->setMaxResults(50);
        return $query->getResult();
    }
    public function findByHistoricoEstadiosNoPresentesEnAt($at)
    {
        $em = $this->getEntityManager();
      
        $query = $em->createQuery('SELECT e FROM BackendBundle:Estadio e
         WHERE e.id NOT IN 
         (SELECT IDENTITY(ath.estadio) FROM AtBundle:AtHistorico ath where ath.at= :at)')
         ->setParameter('at', $at) ; 
         return $query->getResult();
    }
    public function findByEstadiosPuntalesAt($at,$estadio)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT ath FROM AtBundle:AtHistorico ath
        WHERE ath.at= :at and ath.estadio= :estadio')
            ->setParameter('at', $at)
            ->setParameter('estadio', $estadio);
        return $query->getResult();
    }

	
}
