<?php

namespace ATManager\AtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtNotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtNotaRepository extends EntityRepository
{
    public function findByNotasPorAt($at)
    {
        $em = $this->getEntityManager();		  	
        $query = $em->createQuery('SELECT n FROM AtBundle:AtNota n WHERE n.at = :at')
            ->setParameter('at', $at);
        $query->setMaxResults(50);
        return $query->getResult();
    }
}