<?php

namespace ATManager\AtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtRepuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtRepuestoRepository extends EntityRepository
{
    public function findByRepuestosPorAt($at)
    {
        $em = $this->getEntityManager();		  	
        $query = $em->createQuery('SELECT r FROM AtBundle:AtRepuesto r WHERE r.at = :at')
            ->setParameter('at', $at);
        $query->setMaxResults(50);
        return $query->getResult();
    }
}
