<?php

namespace ATManager\AtBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtServicioTerceroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtServicioTerceroRepository extends EntityRepository
{
    public function findByServiciosPorAt($at)
    {
        $em = $this->getEntityManager();		  	
        $query = $em->createQuery('SELECT s FROM AtBundle:AtServicioTercero s WHERE s.at = :at')
            ->setParameter('at', $at);
        $query->setMaxResults(50);
        return $query->getResult();
    }
}
