<?php

namespace ATManager\PatrimonioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatrimonioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatrimonioRepository extends EntityRepository
{
	public function findByFiltroPatrimonio($descripcion, $clasificacion, $local, $marca)
	{

		$em = $this->getEntityManager();
		$query = $em->createQueryBuilder()
		->select('p')
		->from('PatrimonioBundle:Patrimonio','p')
		->where('p.clasificacion = :clasif')
		->setParameter('clasif',$clasificacion)
		->getQuery();
		return $query->getResult();
	}
}
