<?php

namespace ATManager\PatrimonioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatrimonioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatrimonioRepository extends EntityRepository
{
	public function findByFiltroPatrimonio($numero, $descripcion, $observacion, $serial, $clasificacion, $local, $marca)
	{

		$em = $this->getEntityManager();
		$query = $em->createQueryBuilder()
		->select('p')
		->from('PatrimonioBundle:Patrimonio','p')
		->where('1 = 1');
		if ($numero)
		{
		$query->andWhere('p.id = :id');
		$query->setParameter('id',$numero);
		}
		if ($descripcion)
		{
		$query->andWhere('p.descripcion LIKE :descripcion');
		$query->setParameter('descripcion','%'.$descripcion.'%');
		}
		if ($observacion)
		{
		$query->andWhere('p.observacion LIKE :observacion');
		$query->setParameter('observacion','%'.$observacion.'%');
		}
		if ($serial)
		{
		$query->andWhere('p.serial LIKE :serial');
		$query->setParameter('serial','%'.$serial.'%');
		}
		if ($clasificacion)
		{	
		$query->andWhere('p.clasificacion = :clasif');
		$query->setParameter('clasif',$clasificacion);
	    }
	    if ($local)
	    {
    	$query->andWhere('p.local = :local');
		$query->setParameter('local',$local);
	    }
	    if ($marca)
	    {
    	$query->andWhere('p.marca = :marca');
		$query->setParameter('marca',$marca);
	    }

		$query->setMaxResults(500);
		$query = $query->getQuery();
		return $query->getResult();
	}

	
	public function findUltimoPatrimonio()
	{
		$em = $this->getEntityManager();
		$query = $em->createQueryBuilder()
		->select('p')
		->from('PatrimonioBundle:Patrimonio','p')
	    ->orderBy('p.id','DESC')
        ->setMaxResults(1);
        $query = $query->getQuery();
	    return $query->getOneOrNullResult();
	}
}
